### ISSUE TITLE
How to calibrate volume levels?

### ISSUE THREAD

**Issue by kevingrahamtech** [pschatzmann/ESP32-A2DP#16]
I'm using this library on an ESP32 and streaming audio from my phone. My question is how would you adjust the volume so that it has a better range of values available? The lowest volume level on my phone is pretty loud right now, is this adjustable in the code?
Thanks for your work on this library @pschatzmann !

**Comment by pschatzmann** [comment]
I am feeding an Amplifier from a DAC, so I don't have this problem because I can always adjust the volume on the Amplifier.

There isno volume control in the API but I suggest that you have a look at the void  BluetoothA2DPSink::audio_data_callback(const uint8_t *data, uint32_t len)  method:
You could multiply the data with a factor which is < 1.0 which should bring the volume down.

There is already some logic for the Internal DAC which should guide you how this can be done...
