### ISSUE TITLE
crash after end()

### ISSUE THREAD

**Issue by askarigtec** [pschatzmann/ESP32-A2DP#587]
### Problem Description

I have tried and after end on Source mode, it's crashed. and another problem, i cannot connect to a sony headphone by name of device and how to discover devices. i config i2s on slave mode and use a2dp on source mode to transfer audio data. i think setting i2s speed is not working property, i could not change . it is 44100. and after dissconnect(), it is connected again. but i did set_auto_reconnect(false).

### Device Description

wroom 4mb

### Sketch

```cpp
a2dp_.disconnect();
a2dp_.end();
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

PIO default

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Please to not ignore the requested information! 

It is almost impossible to understand what your issue is and absolutely impossible for me to reproduce it, so please provide a short sketch that demonstrates your problems with some clear instructions. 
Also provide the proper version information, that you can find in the log when you compile the  sketch!

Here a couple of comments:

- don't call disconnect w/o waiting for a state change before you call end or better just call end which does the very same thing properly!
- your comment about the sample rate do not make any sense: As you can find in the readme the only supported sample rate is 44100, so if you provide anything other it will not work properly.
-
